Algoritmo "atv7_exercicio1"
// Disciplina   : UC3 ALGORITIMOS
// Professor   : Mateus de Paula Pereira 
// Descrição   : Crie um algoritmo que exiba todos os números inteiros de 1 até 100
// Autor(a)    : Petrus Machado Ramos
// Data atual  : 09/10/2024
Var
// Seção de Declarações das variáveis 
n : inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

para n de 1 ate 100 faca
     escreval(n)
fimpara



Fimalgoritmo