Algoritmo "atv9_exercicio65"
// Disciplina   : UC3 ALGORITIMOS
// Professor   : Mateus de Paula Pereira 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Petrus Machado Ramos
// Data atual  : 21/10/2024
Var
// Seção de Declarações das variáveis 
nm, i : inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
nm <- 100

para i de 1 ate 11 faca
     escreval(nm)
     nm <- nm - 10

fimpara

escreva("Acabou!")


Fimalgoritmo